name: vidbox
description: 本地抖音视频管理器 - 全屏刷着顺手整理本地抖音下载的视频与图片
publish_to: 'none'
version: 0.0.3+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  photo_manager: ^3.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
